// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	SOURCE: any;
	ACCESS_KEY_ID: string | undefined;
	SECRET_ACCESS_KEY: string | undefined;
}
